### ISSUE TITLE
References to service areas

### ISSUE THREAD

**Issue by sarob** [CityOfLosAngeles/mds-core#239]
I found references to service areas in https://github.com/openmobilityfoundation/mds-core/blob/develop/packages/mds-agency/api.ts through cleaning up syntax left over from the OMF repository move.

This appears to be a bug resulting from PR [#203](https://github.com/openmobilityfoundation/mobility-data-specification/pull/203).

I don't know enough about the code to make serious recommendations. But I do know that the https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/agency#service_areas AND the corrected 
https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev/agency#service_areas URLs are incorrect.

**Comment by schnuerle** [comment]
@karcass will these references to service areas be resolved with PR #249?

**Comment by schnuerle** [comment]
@karcass can you check and see if we need this PR #240, or if your PR merged just now takes care of it.
