### ISSUE TITLE
Address potential security issues in dependencies

### ISSUE THREAD

**Issue by jfh01** [CityOfLosAngeles/mds-core#243]
GitHub has identified several `mds-core` dependencies (handlebars and serialize-javascript) with possible security vulnerabilities. Need to review and address if necessary. 

https://github.com/openmobilityfoundation/mds-core/network/alerts

**Comment by marie-x** [comment]
@jfh01 These were corrected in the LADOT fork as soon as they were flagged by GitHub.  No action needed in this repo other than the upcoming catch-up PR.

**Comment by schnuerle** [comment]
FYI only admins on the repo can see the network/alerts link, as it should be.  Wanted to let others know why they can't see the details.

**Comment by jfh01** [comment]
Per @karcass, these will be corrected as part of our `mds-core` transition. Closing this issue.
