### ISSUE TITLE
PROPOSAL: mds-core transition to OMF City Services Working group

### ISSUE THREAD

**Issue by jfh01** [CityOfLosAngeles/mds-core#244]
To date, `mds-core` has been developed primarily by LADOT and their contractor Ellis and Associations. As part of the code contribution from LADOT to OMF, it is intend that `mds-core` be transitioned to management by the OMF City Services Working Group. It is our hope that a community of developers and interested stakeholders can be built around `mds-core`, similar to the community that exists for the Mobility Data Specification itself. That community will drive future development of `mds-core` with continued contribution from LADOT and their contractors.

Here you will find a proposal to the community for how to accomplish this transition:

https://docs.google.com/presentation/d/1y8WzdK4o2iA_v57zoEMgIuyBWqhyp4VufENAUwFlK1s/edit#slide=id.g643cf86fc3_0_0

We are soliciting feedback on this proposal. It will be presented to the City Services Working Group on an upcoming call as well. Please leave questions, comments, and reactions in this issue, or feel free to email jascha@openmobilityfoundation.org directly.

**Comment by schnuerle** [comment]
Work in progress.  Follow along with PR #249 for merger of deployable and testable code to OMF organization.

**Comment by schnuerle** [comment]
Completed
