### ISSUE TITLE
Docs for Authentication Configuration

### ISSUE THREAD

**Issue by jaimeventura** [CityOfLosAngeles/mds-core#261]
Hey,
Im trying to set up a mds-core instance (mds-agency, for now), but i couldn't find documentation on how to configure secrets or public/private keys for jwt token validation, which claims should be set for authentication, ...
The same goes for authorization.

Are there any examples available? Thanks.

**Comment by schnuerle** [comment]
I'm not sure this is clearly documented yet for MDS-core.  You can read about auth details in the MDS repo (eg, in [Agency](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/agency#authorization) or [Provider](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/provider/auth.md)), but that may not be enough detail for you. I'm tagging @karcass here who would know more and could point you in the right direction.

Also note that there may be updates and new features and documentation improvements in this [development branch](https://github.com/lacuna-tech/mds-core) of mds-core.

**Comment by oldschoolsysadmin** [comment]
For the LADOT implementation, we use auth0.com as the JWT issuer - this removes the need for us to manage the secrets and key pairs used in token issuance.  Auth0 has a free tier for evaluating their service - it has low quotas but can be used indefinitely.  Does this help, @jaimeventura ?

**Comment by jaimeventura** [comment]
It does, thanks!, but in my humble opinion, its still short.

Before i continue, let me say that i'm installing mds-core services (starting with mds-agency) using docker-compose only (no k8s, heml, ...)
You're using  auth0, that's cool.
From the little i know about auth0, it encrypts the signatures using its own private keys. auth0 provides a jwks.json file with its public keys, so the service API is able to verify the signature. So, (1) how do i provide/configure the location to that file in my installation, to mds-agency? does it expects it on a default path? Is there a env variable to specify its location?
Also, (2) i was able to generate valid tokens by just using jwt.io, with the following payload, and was actually able to do some requests:
```
{
     "scope": "admin:all test:all",
     "provider_id": "c20e08cf-8488-46a6-a66c-5d8fb827f7e0"
     }
```

But it worked regardless the secret i was using, meaning the signature was not being verified at all.
So, is this some dev mode by default? how do I activate signature verification (i've found a mention to this [here](https://github.com/openmobilityfoundation/mds-core/tree/dev/helm/mds), but im not using k8s)?

And finally (for now), about authorisation, (3) what do I need to configure in auth0 for a RBAC in mds-agency operations?

Feel free to move this to a github conversation. And thanks you for your patience.

**Comment by oldschoolsysadmin** [comment]
Hi @jaimeventura - if you look at https://github.com/openmobilityfoundation/mds-core/blob/dev/helm/mds/templates/auth.yaml, that has the template for setting up authentication with a token issuer via an Istio policy resource (set `jwt.enabled=true` when doing the helm install).  I would recommend not using the other option, `jwt.bypassInternal` - that was a semi-successful attempt to move the JWT auth from the service resources to the namespace ingress and egress.

**Comment by jaimeventura** [comment]
@invertigo Thanks.
I dont want to be too picky about this and, please, let me stress that im willing to use mds-core and help the effort to develop it.
But you're assuming i know about helm and that i'm able to extract information on how to run it by looking/interpreting at heml  configuration files.
Well, that's not the case. I mentioned earlier i was using regular docker-compose. Im trying to get it up and running without 'automagic' tools that hides the details.
Of course, i can (and will) learn about helm. And will most likely need it in a production environment.
For now, but i would rather be able to get it up and running by reading a 'regular' form of documentation (no offence!).
Anyway, thanks!

**Comment by jaimeventura** [comment]
Hey all,
I was able to get it running. We ended up using openresty as the gateway.
I'll be glad to document the process.
Thank you

**Comment by schnuerle** [comment]
That's great @jaimeventura that you got mds-core up and running! Thank you for your persistence. If you do have time to document what you did and any hurdles you overcame, we can incorporate that into the repo or a wiki page. Who were you setting it up for?

**Comment by jaimeventura** [comment]
>If you do have time to document what you did and any hurdles you overcame, we can incorporate that into the repo or a wiki page.
Sure. Should I target this repo or [fork E&A maintains](https://github.com/lacuna-tech/mds-core)?
>Who were you setting it up for?
The City of Porto, Portugal.

**Comment by schnuerle** [comment]
@jaimeventura If you could make a Google Doc or equivalent that writes up your process, hurdles, etc, and link to it here, then we at the OMF can use that to incorporate your changes into one of the repos and/or a wiki page.
