### ISSUE TITLE
Add Circ provider to mds-core

### ISSUE THREAD

**Issue by cafsenra** [CityOfLosAngeles/mds-core#264]
Hi,

I belong to APD, who is responsible by implement your solution on Oporto, Portugal.

We need to use Circ provider on MDS-Core.

The Circ provider is defined here:
https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv

But we found that is not in the code, for example, here:
https://github.com/openmobilityfoundation/mds-core/blob/dev/packages/mds-providers/index.ts

Can you please add this provider?

Thank you!

**Comment by schnuerle** [comment]
Thanks @cafsenra. This raises a good point that maybe these should not be hardcoded here, but maybe pulled from the providers.csv file? Though that might be a challenge.  

Also noticed that these should be added to providers.csv, per this [code comment](https://github.com/openmobilityfoundation/mds-core/blob/059b42a0f6454c6bc87a8f9d5a0c6922fe77a677/packages/mds-providers/index.ts#L23).

Also to note here, that this repo is behind the more [updated version here](https://github.com/lacuna-tech/mds-core) and needs to be merged and may fix issues like this. Related is a question in #268 that asks about the status of this repo, which I will answer shortly.

@karcass any other feedback you have here would be welcome.

**Comment by jaimeventura** [comment]
Hey,
I've just created the issue in the repo you mentioned:

https://github.com/lacuna-tech/mds-core/issues/577

Unrelated, i've also added another one(https://github.com/lacuna-tech/mds-core/issues/576). I would be most appreciated if someone could have a look at it too.

**Comment by cafsenra** [comment]
Thanks @schnuerle for your reply. I assume that that this issue will be solved in the repo you mentioned. Thanks @jaimeventura for opening this issue on that repo. I will close this issue here.
